apiVersion: v1
kind: Secret
metadata:
  name: miniticket-secrets
  namespace: miniticket
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: bondstone
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
