apiVersion: v1
kind: Secret
metadata:
  name: miniticket-secrets
  namespace: miniticket
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: bondstone
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin

  KC_ISSUER: "https://auth.miniticket.online/realms/miniTicket"
  KC_JWK_URI: "http://keycloak:8080/realms/miniTicket/protocol/openid-connect/certs"
