apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: miniticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args:
            - start-dev
          ports:
            - containerPort: 8080
          env:
            # ✅ Enable HTTP (important for start-dev)
            - name: KC_HTTP_ENABLED
              value: "true"

            # ✅ VERY IMPORTANT: host only (NOT full URL)
            - name: KC_HOSTNAME
              value: "https://auth.miniticket.online"

            - name: KC_HOSTNAME_STRICT
              value: "false"

            - name: KC_PROXY_HEADERS
              value: "xforwarded"

            # Admin credentials
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: miniticket-secrets
                  key: KEYCLOAK_ADMIN

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniticket-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: miniticket
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080

