apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: miniticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args:
            - start-dev
          ports:
            - containerPort: 8080
          env:
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "https://auth.miniticket.online"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: JAVA_OPTS_APPEND
              value: "-Xms256m -Xmx512m"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: miniticket-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniticket-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: miniticket
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
